### ISSUE TITLE
[lower priority but actionable] Add new endpoint for skipping workflow

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/workflow-server-rails#782]
This PR in common-accessioning adds some logic to the `ocrWF:start-ocr` robot that skips the rest of the workflow based on a given condition, by setting all remaining steps to `skipped` in reverse order.

If we ever need to do this again, it makes sense to add a new API endpoint to workflow-server-rails to do this.  You'd pass in the name of the workflow, and it would set all remaining steps to skipped (optionally skipping a step you pass in, which could be the step making the call).

We would also need to update `dor-workflow-client` to wrap the new API call in a method.  Create a separate ticket or do as part of this work.

See https://github.com/sul-dlss/common-accessioning/pull/1262

When available, then update common-accessioning so that the start-ocr step uses the new endpoint.

**Comment by jmartin-sul** [comment]
* this is lower priority than all the other work cycle work (in progress development and subsequent debugging) since we have a working, if slightly suboptimal, solution right now on common-accessioning `main`
* if someone does pick this up, please don't change the call for this to WFS that's made from common-accessioning while other testing is happening, to keep from confounding results in the home stretch.

**Comment by jmartin-sul** [comment]
i think this is done as of https://github.com/sul-dlss/common-accessioning/issues/1299 ?
